Entities/Film.cs
using Netflex.Entities.Abstractions;

namespace Netflex.Entities;

public class Film : Entity
{
    public required string Title { get; set; }
    public string? About { get; set; }
    public string? Poster { get; set; }
    public string? Path { get; set; }
    public string? Trailer { get; set; }
    public int ProductionYear { get; set; }
    public Guid? AgeCategoryId { get; set; }
    public TimeSpan HowLong { get; set; }
    public DateTime CreatedAt { get; set; }

    public ICollection<FavoriteFilms> FavoriteFilms { get; set; } = [];
}

Models/Film/CreateFilmModel.cs
using System.ComponentModel.DataAnnotations;

namespace Netflex.Models.Film;

public class CreateFilmModel
{
    [Required, StringLength(100, MinimumLength = 3)]
    public required string Title { get; set; }
    [StringLength(1000)]
    public string? About { get; set; }
    [RegularExpression(@"^https:\/\/www\.youtube\.com\/watch\?v=(.*?)(?:\&(.*))?$", ErrorMessage = "Trailer must be a valid Youtube link")]
    [StringLength(1000)]
    public string? Trailer { get; set; }
    [Required, Range(1, int.MaxValue, ErrorMessage = "Production year must be greater than 0")]
    public int ProductionYear { get; set; }
    [Required(ErrorMessage = "The Age category field is required.")]
    public string? AgeCategoryId { get; set; }
    [MaxFileSize(5 * 1024 * 1024), AllowedExtensions([".jpg", ".png", ".jpeg"])]
    public IFormFile? Poster { get; set; }
    [MaxFileSize(5 * 1024 * 1024), AllowedExtensions([".m3u8"])]
    public IFormFile? File { get; set; }
}

Models/Film/CreateFilmViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Netflex.Models.Film;

public class CreateFilmViewModel
{
    [Required, StringLength(100, MinimumLength = 3)]
    public required string Title { get; set; }
    [StringLength(1000)]
    public string? About { get; set; }
    [RegularExpression(@"^https:\/\/www\.youtube\.com\/embed\/(.*?)(?:\?(.*))?$", ErrorMessage = "Trailer must be a valid Youtube embed link")]
    [StringLength(1000)]
    public string? Trailer { get; set; }
    [Required, Range(1, int.MaxValue, ErrorMessage = "Production year must be greater than 0")]
    public int ProductionYear { get; set; }
    [Required(ErrorMessage = "The Age category field is required.")]
    public string? AgeCategoryId { get; set; } = string.Empty;
    [MaxFileSize(5 * 1024 * 1024), AllowedExtensions([".jpg", ".png", ".jpeg"])]
    public IFormFile? Poster { get; set; }
    [MaxFileSize(5 * 1024 * 1024), AllowedExtensions([".m3u8"])]
    public IFormFile? File { get; set; }
    public List<Guid>? ActorIds { get; set; } = new();
    public List<Guid>? GenreIds { get; set; } = new();
    public List<Guid>? CountryIds { get; set; } = new();
}

Models/Film/DetailFilmViewModels.cs
namespace Netflex.Models.Film;

public class DetailFilmViewModel
{
    public required Guid Id { get; set; }
    public required string Title { get; set; }
    public string? About { get; set; }
    public string? Poster { get; set; }
    public string? Path { get; set; }
    public string? Trailer { get; set; }
    public int ProductionYear { get; set; }
    public string? AgeCategory { get; set; }
    public bool IsFollowed { get; set; }
    public DateTime CreatedAt { get; set; }
}

Models/Film/EditFilmModel.cs
using System.ComponentModel.DataAnnotations;

namespace Netflex.Models.Film;

public class EditFilmModel
{
    [Required, StringLength(100, MinimumLength = 3)]
    public required string Title { get; set; }
    [StringLength(1000)]
    public string? About { get; set; }
    [StringLength(1000)]
    public string? Trailer { get; set; }
    [Required]
    public int ProductionYear { get; set; }
    public string? AgeCategoryId { get; set; }
    public IFormFile? Poster { get; set; }
    public IFormFile? File { get; set; }
}

Models/Film/EditFilmViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Netflex.Models.Film;

public class EditFilmViewModel
{
    public Guid Id { get; set; }
    [Required, StringLength(100, MinimumLength = 3)]
    public required string Title { get; set; }
    [StringLength(1000)]
    public string? About { get; set; }
    [RegularExpression(@"^https:\/\/www\.youtube\.com\/embed\/(.*?)(?:\?(.*))?$", ErrorMessage = "Trailer must be a valid Youtube embed link")]
    [StringLength(1000)]
    public string? Trailer { get; set; }
    [Required, Range(1, int.MaxValue, ErrorMessage = "Production year must be greater than 0")]
    public int ProductionYear { get; set; }
    [Required(ErrorMessage = "The Age category field is required.")]
    public Guid? AgeCategoryId { get; set; }
    [MaxFileSize(5 * 1024 * 1024), AllowedExtensions([".jpg", ".png", ".jpeg"])]
    public IFormFile? Poster { get; set; }
    [MaxFileSize(5 * 1024 * 1024), AllowedExtensions([".m3u8"])]
    public IFormFile? File { get; set; }
    public string? PosterUrl { get; set; }
    public string? FileUrl { get; set; }
    public List<Guid>? ActorIds { get; set; } = new();
    public List<Guid>? GenreIds { get; set; } = new();
    public List<Guid>? CountryIds { get; set; } = new();
}

Models/Film/FilmViewModel.cs
namespace Netflex.Models.Film;

public class FilmViewModel
{
    public required Guid Id { get; set; }
    public required string Title { get; set; }
    public string? Poster { get; set; }
    public string? Path { get; set; }
    public string? Trailer { get; set; }
    public int ProductionYear { get; set; }
    public string? AgeCategory { get; set; }
    public DateTime CreatedAt { get; set; }

}

Controllers/FilmController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Netflex.Database;
using Netflex.Models;
using Netflex.Models.Film;
using X.PagedList.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Netflex.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class FilmController : BaseController
    {
        private const int PAGE_SIZE = 12;
        private readonly ApplicationDbContext _context;
        private readonly IFollowRepository _followRepository;
        private readonly UserManager<User> _userManager;

        public FilmController(IFollowRepository followRepository, IUnitOfWork unitOfWork, UserManager<User> userManager, ApplicationDbContext context)
            : base(unitOfWork)
        {
            _followRepository = followRepository;
            _userManager = userManager;
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> GetFilms(int? page, Guid? genreId, Guid? countryId, int? year, string? keyword)
        {
            try
            {
                int pageNumber = page ?? 1;
                var filmQuery = _unitOfWork.Repository<Film>().Entities.AsQueryable();

                if (genreId.HasValue)
                {
                    var filmGenreEntities = await _context.FilmGenres
                        .Where(fg => fg.GenreId == genreId)
                        .Select(fg => fg.FilmId)
                        .ToListAsync();
                    filmQuery = filmQuery.Where(film => filmGenreEntities.Contains(film.Id));
                }

                if (countryId.HasValue)
                {
                    var filmCountryEntities = await _context.FilmCountries
                        .Where(fc => fc.CountryId == countryId)
                        .Select(fc => fc.FilmId)
                        .ToListAsync();
                    filmQuery = filmQuery.Where(film => filmCountryEntities.Contains(film.Id));
                }

                if (year.HasValue)
                {
                    filmQuery = filmQuery.Where(film => film.ProductionYear == year.Value);
                }

                if (!string.IsNullOrEmpty(keyword))
                {
                    filmQuery = filmQuery.Where(film => film.Title.ToLower().Contains(keyword.ToLower())
);
                }


                var models = await filmQuery
      //.OrderByDescending(f => f.CreatedAt)
      .Select(film => new FilmViewModel
      {
          Id = film.Id,
          Title = film.Title,
          Poster = film.Poster,
          Path = film.Path,
          Trailer = film.Trailer,
          ProductionYear = film.ProductionYear,
          CreatedAt = film.CreatedAt
      })
      .ToListAsync(); // Note the use of ToListAsync instead of ToPagedListAsync

                var pagedModels = models.ToPagedList(pageNumber, PAGE_SIZE);

                string genreName = genreId.HasValue
                    ? await _unitOfWork.Repository<Genre>().Entities
                        .Where(g => g.Id == genreId)
                        .Select(g => g.Name)
                        .FirstOrDefaultAsync() ?? "Unknown Genre"
                    : "";

                string countryName = countryId.HasValue
                    ? await _unitOfWork.Repository<Country>().Entities
                        .Where(c => c.Id == countryId)
                        .Select(c => c.Name)
                        .FirstOrDefaultAsync() ?? "Unknown Country"
                    : "";

                string yearTitle = year.HasValue ? $"{year}" : "";
                string title = $"{genreName} {countryName} {yearTitle}".Trim();
                if (string.IsNullOrEmpty(title))
                {
                    title = "Phim lẻ";
                }

                return Ok(new
                {
                    items = pagedModels,
                    pageNumber,
                    pageSize = PAGE_SIZE,
                    totalItems = pagedModels.TotalItemCount,
                    totalPages = pagedModels.PageCount,
                    title
                });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { message = "An error occurred while fetching films", error = ex.Message });
            }
        }

        [HttpGet("latest")]
        public async Task<IActionResult> GetLatestFilms(int? page)
        {
            try
            {
                int pageNumber = page ?? 1;

                var filmQuery = _unitOfWork.Repository<Film>().Entities
                    .OrderByDescending(f => f.CreatedAt)
                    .Select(film => new FilmViewModel
                    {
                        Id = film.Id,
                        Title = film.Title,
                        Poster = film.Poster,
                        Path = film.Path,
                        Trailer = film.Trailer,
                        ProductionYear = film.ProductionYear,
                        CreatedAt = film.CreatedAt
                    });

                var models = await filmQuery.ToListAsync();
                var pagedModels = models.ToPagedList(pageNumber, PAGE_SIZE);

                return Ok(new
                {
                    items = pagedModels,
                    pageNumber,
                    pageSize = PAGE_SIZE,
                    totalItems = pagedModels.TotalItemCount,
                    totalPages = pagedModels.PageCount,
                    title = "Phim mới nhất"
                });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { message = "An error occurred while fetching latest films", error = ex.Message });
            }
        }


        [HttpGet("{id}")]
        public async Task<IActionResult> GetFilmDetail(Guid? id)
        {
            try
            {
                if (id == null || id == Guid.Empty)
                    return BadRequest(new { message = "Invalid Film ID" });

                var film = await _unitOfWork.Repository<Film>().Entities
                    .FirstOrDefaultAsync(m => m.Id.Equals(id));

                if (film == null)
                    return NotFound(new { message = "Film not found" });

                var user = await _userManager.GetUserAsync(User);
                bool isFollowed = false;

                if (user != null)
                {
                    var existingFollow = await _followRepository.GetByUserIdAndFilmIdAsync(user.Id, film.Id);
                    isFollowed = existingFollow != null;
                }

                var model = new DetailFilmViewModel
                {
                    Id = film.Id,
                    Title = film.Title,
                    About = film.About,
                    Poster = film.Poster,
                    Path = film.Path,
                    Trailer = film.Trailer,
                    ProductionYear = film.ProductionYear,
                    IsFollowed = isFollowed,
                    CreatedAt = film.CreatedAt
                };

                var actorIds = await _context.FilmActors
                    .Where(fa => fa.FilmId == id)
                    .Select(fa => fa.ActorId)
                    .ToListAsync();

                var actors = await _unitOfWork.Repository<Actor>().Entities
                    .Where(a => actorIds.Contains(a.Id))
                    .ToListAsync();

                var countryIds = await _context.FilmCountries
                    .Where(fc => fc.FilmId == id)
                    .Select(fc => fc.CountryId)
                    .ToListAsync();

                var countries = await _unitOfWork.Repository<Country>().Entities
                    .Where(a => countryIds.Contains(a.Id))
                    .Select(c => c.Name)
                    .ToListAsync();

                var genreIds = await _context.FilmGenres
                    .Where(fg => fg.FilmId == id)
                    .Select(fg => fg.GenreId)
                    .ToListAsync();

                var genres = await _unitOfWork.Repository<Genre>().Entities
                    .Where(g => genreIds.Contains(g.Id))
                    .ToListAsync();

                var relatedFilmIds = await _context.FilmGenres
                    .Where(fg => genreIds.Contains(fg.GenreId) && fg.FilmId != id)
                    .Select(fg => fg.FilmId)
                    .Distinct()
                    .Take(50)
                    .ToListAsync();

                var relatedFilms = await _unitOfWork.Repository<Film>().Entities
                    .Where(f => relatedFilmIds.Contains(f.Id))
                    .OrderBy(f => f.Title)
                    .Take(10)
                    .Select(f => new FilmViewModel
                    {
                        Id = f.Id,
                        Title = f.Title,
                        Poster = f.Poster,
                        Path = f.Path,
                        Trailer = f.Trailer,
                        ProductionYear = f.ProductionYear,
                        CreatedAt = f.CreatedAt
                    })
                    .ToListAsync();

                return Ok(new
                {
                    film = model,
                    actors,
                    countries,
                    genres,
                    relatedFilms
                });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { message = "An error occurred while fetching film details", error = ex.Message });
            }
        }
    }
}

Views/Film/Edit.cshtml
@model EditFilmViewModel
@{
    ViewData["Title"] = "Edit Film";
    Layout = "_Layout";
}
@section Styles {
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <style>
        .select2-container--default .select2-selection--multiple {
            min-height: 38px;
        }

        .select2-container--default .select2-results__option {
            color: black !important;
        }

        .select2-container--default .select2-results__option--highlighted {
            background-color: #d1d1d1 !important;
        }

        .select2-container--default .select2-selection--multiple .select2-selection__choice {
            color: black;
        }
    </style>
}
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="film" asp-action="index">Phim lẻ</a></li>
            <li class="breadcrumb-item active" aria-current="page">@Model.Title</li>
        </ol>
    </nav>
    <div class="row">
        <div class="col-md-4">
            <form method="POST" enctype="multipart/form-data" asp-controller="film" asp-action="edit">
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="PosterUrl" />
                <input type="hidden" asp-for="FileUrl" />

                <div class="form-group required">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" type="text" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="About" class="control-label"></label>
                    <textarea asp-for="About" class="form-control" rows="3"></textarea>
                    <span asp-validation-for="About" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Trailer" class="control-label"></label>
                    <input asp-for="Trailer" type="text" class="form-control"
                        placeholder="https://www.youtube.com/watch?v=example" />
                    <span asp-validation-for="Trailer" class="text-danger"></span>
                </div>
                <div class="form-group required">
                    <label asp-for="ProductionYear" class="control-label"></label>
                    <input asp-for="ProductionYear" class="form-control" value="2025" placeholder="2025" />
                    <span asp-validation-for="ProductionYear" class="text-danger"></span>
                </div>

                @* <div class="form-group required">
                    <label asp-for="AgeCategoryId" class="control-label">Age Category</label>
                    <select class="form-select" asp-for="AgeCategoryId">
                        <option disabled selected>Select a age category</option>
                        <option value="1">0+ Suitable for all ages</option>
                        <option value="2">3+ Designed for very young children</option>
                        <option value="2">7+ Parental guidance suggested</option>
                        <option value="3">12+ May contain moderate violence</option>
                        <option value="3">16+ Stronger themes, violence</option>
                        <option value="3">18+ Restricted to adults</option>
                    </select>
                    <span asp-validation-for="AgeCategoryId" class="text-danger"></span>
                </div> *@
                <div class="form-group required">
                    <label class="control-label">Age Category</label>
                    <select asp-for="AgeCategoryId" class="form-select">
                        @foreach (var age in ViewBag.AgeCategories)
                        {
                            <option value="@age.Id" selected="@(Model.AgeCategoryId == age.Id ? "selected" : null)">
                                @age.Name</option>
                        }

                    </select>
                </div>
                <div class="form-group">
                    <label asp-for="Poster" class="control-label"></label>
                    <input asp-for="Poster" type="file" class="form-control" id="posterUpload" />
                    <span asp-validation-for="Poster" class="text-danger"></span>

                    <div class="mt-2">
                        @if (!string.IsNullOrEmpty(Model.PosterUrl))
                        {
                            <img id="posterCurrentImage" src="@Url.Content(Model.PosterUrl)" alt="Current Poster"
                                class="img-fluid rounded shadow-sm mw-100 mb-2">
                        }
                        <img id="posterPreview" src="#" alt="Preview Image"
                            class="img-fluid rounded shadow-sm d-none mw-100">
                    </div>

                    <input type="hidden" asp-for="PosterUrl" id="posterUrlInput" />
                    <input type="hidden" name="KeepExistingPoster" id="keepExistingPoster" value="true" />
                </div>

                <div class="form-group required">
                    <label class="control-label">Actors</label>
                    <select asp-for="ActorIds" class="form-select select2-multiple" asp-items="ViewBag.Actors"
                        multiple></select>
                </div>

                <div class="form-group required">
                    <label class="control-label">Genres</label>
                    <select asp-for="GenreIds" class="form-select select2-multiple" asp-items="ViewBag.Genres"
                        multiple></select>
                </div>

                <div class="form-group required">
                    <label class="control-label">Countries</label>
                    <select asp-for="CountryIds" class="form-select select2-multiple" asp-items="ViewBag.Countries"
                        multiple></select>
                </div>
                
                <div class="form-group">
                    <label asp-for="File" class="control-label">File .m3u8</label>
                    <input asp-for="File" type="file" class="form-control" />
                    <span asp-validation-for="File" class="text-danger"></span>
                </div>

                <br />
                <button type="submit" class="btn btn-primary mb-3">Update</button>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.select2-multiple').select2({
                placeholder: "Select options",
                allowClear: true,
                width: '100%'
            });

            $("#posterUpload").change(function () {
                let input = this;
                if (input.files && input.files[0]) {
                    let reader = new FileReader();
                    reader.onload = function (e) {
                        $("#posterPreview").attr("src", e.target.result).removeClass("d-none");
                        $("#posterCurrentImage").addClass("d-none");
                        $("#keepExistingPoster").val("false");
                    };
                    reader.readAsDataURL(input.files[0]);
                } else {
                    $("#posterPreview").addClass("d-none");
                    $("#posterCurrentImage").removeClass("d-none");
                    $("#keepExistingPoster").val("true");
                }
            });
        });
    </script>
}

Views/Film/SearchByTitle.cshtml
@model IPagedList<DetailFilmViewModel>
@using X.PagedList.Mvc.Core

@{
	Layout = "_Layout";
}
<style>

	.img-fluid.rounded {
		width: 180px;
		height: 180px;
		object-fit: cover;
		border-radius: 8px;
	}

	.search-box {
		display: flex;
		align-items: center;
		justify-content: center;
		margin-bottom: 20px;
	}

	.search {
		width: 100%;
		background: transparent;
		border: none;
		outline: none;
	}

	.search-icon {
		background: none;
		border: none;
		color: white;
		cursor: pointer;
	}

	.pagination {
		margin-top: 20px;
	}

	.page-item .page-link {
		color: white;
		background: rgba(255, 255, 255, 0.1);
		border: none;
		margin: 0 5px;
	}

	.page-item.active .page-link {
		background: #0D6EFD;
	}
</style>

<div class="container">
	<h2 class="text-white text-center mt-3">@ViewData["Title"]</h2>

	@if (Model.Count == 0)
	{
		<h4 class="text-white text-center mt-4 mb-4">Phim đang được cập nhật!</h4>
	}
	else
	{
		<h4 class="text-white mt-4 mb-4">@ViewData["Title"] mới cập nhật</h4>

		<form class="search-box" action="@Url.Action("SearchByTitle", "Film")">
			<input class="search" type="text" placeholder="Tìm kiếm phim..." name="searchTitle">
			<button type="submit" class="search-icon"><i class="fa-solid fa-magnifying-glass"></i></button>
		</form>

		<div class="row">
			@foreach (var film in Model)
			{

				<a href="@Url.Action("Detail", "Film", new { id = film.Id })" class="text-white">
					<div class="card bg-transparent text-white p-1 mb-1">
						<div class="row g-0">
							<div class="col-md-3">
								<div class="position-relative">
									<img src="@film.Poster" alt="@film.Title" class="img-fluid rounded">
								</div>
							</div>
							<div class="col-md-9">
								<div class="card-body">
									<h5 class="card-title film-title">
										@(film.Title)
									</h5>
									<p class="card-text film-age">@film.AgeCategory</p>
									<p class="card-text film-about">@film.About</p>
								</div>
							</div>
						</div>
					</div>
				</a>
				<hr class="text-white" />
			}
		</div>

		<nav class="d-flex justify-content-center pagination">
			@Html.PagedListPager(Model, page => Url.Action("SearchByTitle", new { page }), new PagedListRenderOptions
{
	LiElementClasses = new string[] { "page-item" },
	PageClasses = new string[] { "page-link" }
})
		</nav>
	}
</div>